AWSTemplateFormatVersion: '2010-09-09-OC'

Parameters:
  bucketName:
    Type: String
  flowlogsMinRetentionInDays:
    Type: Number
    Default: 90
  flowLogsRetentionMode:
    Type: String
    Default: GOVERNANCE

Resources:
  FlowLogsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Ref bucketName
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      ObjectLockEnabled: true
      ObjectLockConfiguration:
        ObjectLockEnabled: Enabled
        Rule:
          DefaultRetention:
            Days: !Ref flowlogsMinRetentionInDays
            Mode: !Ref flowLogsRetentionMode

  FlowLogsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FlowLogsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AWSLogDeliveryWrite
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action: s3:PutObject
            Resource:
              - Fn::EnumTargetAccounts AllBinding '${FlowLogsBucket.Arn}/AWSLogs/${account}/*'
              - Fn::EnumTargetAccounts AllBinding '${FlowLogsBucket.Arn}/AWSLogs/aws-account-id=${account}/*'
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                'aws:SourceAccount':
                  - Fn::EnumTargetAccounts AllBinding '${account}'
              ArnLike:
                'aws:SourceArn':
                  - Fn::EnumTargetAccounts AllBinding 'arn:aws:logs:*:${account}:*'
          - Sid: AWSLogDeliveryAclCheck
            Effect: Allow
            Principal:
              Service: delivery.logs.amazonaws.com
            Action:
              - s3:GetBucketAcl
              - s3:ListBucket
            Resource:
              - !GetAtt FlowLogsBucket.Arn
            Condition:
              StringEquals:
                'aws:SourceAccount':
                  - Fn::EnumTargetAccounts AllBinding '${account}'
              ArnLike:
                'aws:SourceArn':
                  - Fn::EnumTargetAccounts AllBinding 'arn:aws:logs:*:${account}:*'

